# Available packages failed on my system.
# If charset is used as an argument
# the corresponding input file has to be encoded
# in the given charset as well.

# For instance, exiftoolr::exifread() sends arguments, args and paths
# to an argument encoded in UTF-8. However, when using
# exiftool on a Windows machine using iso-8859-1 as locale (my setup) from R >= 4.3,
# the argument file has to include the file paths encoded
# as ANSI and not UTF-8.
# The convert_encoding argument does this character encoding conversion.
# exiftool_read() uses external argument files,
# and response from exiftool (executable must as default be stored in current
# workin directory) is stored in an external JSON-file.
# Data as imported from the JSON-file with jsonlite::fromJSON().
# The two external files generated by the function call are deleted on exit,
# unless delete_temp_files = FALSE.
#' @export
exiftool_read <- function(
    path,
    args = c(
      "-j", "-q", "-n", "-alldates"),
    charset = "cp1252",
    tags = c("filename", "filesize", "imagesize"),
    exiftool_path = "exiftool(-k).exe",
    args_file = "tmp_exif_data.arg",
    output_file = "tmp_exif_data.json",
    convert_encoding = TRUE,
    current_encoding = "utf-8",
    target_encoding = "iso-8859-1",
    clean_names = TRUE,
    delete_temp_files = TRUE) {

  if (convert_encoding) {
    path <- iconv(path, current_encoding, target_encoding)
  }

  if(!is.null(charset)) {
    args <- c(args, "-charset", paste("filename", charset, sep = "="))
  }

  if (!is.null(tags)) {
    tags <- paste0("-", tags)
  }

  # Send arguments, tags and paths to a temporary *.arg-file
  write.table(
    c(args, tags, path),
    args_file,
    quote = FALSE, row.names = FALSE, col.names = FALSE)

  # System command, response stored in JSON-format
  exif_call <- system2(
    exiftool_path,
    args = c("-@", args_file),
    stdout = output_file)

  # Import data in JSON-format
  exif_data_parse <- jsonlite::fromJSON(output_file) %>%
    as_tibble() %>%
    relocate(FileName)

  if (clean_names) {
    exif_data_parse <- exif_data_parse %>%
      janitor::clean_names()
  }

  # Delete temporary files
  if (delete_temp_files) {
    on.exit(unlink(c(args_file, output_file)))
  }

  exif_data_parse
}
